### ISSUE TITLE
Not working with Latest Tailwind and Purge

### ISSUE THREAD

**Issue by SohanChotia** [karolis-sh/tailwind-bootstrap-grid#84]
Hi, I have installed Tailwind and this along with postcss all globally and properly configured it

But it doesn't generate a single class related to grids..

`module.exports = {
//  mode: 'jit',
  corePlugins: {
   container: false,
  },
  purge: {
    enabled: true,
    content: [
      './index.php',
      './results.php',
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {    
  },
  variants: {
    extend: {},
  },
  plugins: [
    //require('@tailwindcss/forms')({ strategy: 'class', })
    require('@tailwindcss/forms'),
    require('tailwind-bootstrap-grid'),
  ],
}`

**Comment by karolis-sh** [comment]
Disable the purge, I guess you're just purging too much. Otherwise, provide a reproduction example.

**Comment by SohanChotia** [comment]
```
const plugin = require('tailwindcss/plugin')

module.exports = {
  mode: 'jit',
  corePlugins: {
   container: false,
  },
  purge: {
    enabled: true,
    content: [
      './index.php',
      './results.php',
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: { },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('tailwind-bootstrap-grid'),
    plugin(function({ addComponents }) {
      var row = {
        '.row': {
          '--bs-gutter-x': '1.5rem',
          '--bs-gutter-y': 0,
          display: 'flex',
          flexWrap: 'wrap',
          marginTop: 'calc(var(--bs-gutter-y) * -1)',
          marginRight: 'calc(var(--bs-gutter-x) / -2)',
          marginLeft: 'calc(var(--bs-gutter-x) / -2)',
          '& > *': {
            boxSizing: 'border-box',
            flexShrink: 0,
            width: '100%',
            maxWidth: '100%',
            paddingRight: 'calc(var(--bs-gutter-x) / 2)',
            paddingLeft: 'calc(var(--bs-gutter-x) / 2)',
            marginTop: 'var(--bs-gutter-y)',
          },
        }
      }
      addComponents(row)
    })
  ],
}
```
Tailwind: **2.2.4**
PostCss: **8.1.0**
Node: **12.16.1**

I have this config, and all packages are installed globaly, with npm -g command
its weird, tailwind forms plugin works,
even custom plugin  where I added same code from this plugin for rows , works and outputs css for rows,
but no classes from this plugin.

And I have row and col classes in index.php file, so i don't think its too much purging, or am I missing something ..

**Comment by karolis-sh** [comment]
Please disable the purging.

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by karolis-sh** [comment]
I've added a purge use-case example (https://github.com/karolis-sh/tailwind-bootstrap-grid/tree/master/samples/purge) and everything works as expected.

If **when purging disabled**, you see the built grid classes it means you aren't writing purgeable HTML or the purge setup is invalid. Otherwise, there's something wrong with the build setup.

**Comment by SohanChotia** [comment]
Its funny enough, I noticed it very late.

This doesn't work
```
plugins: [
     require('tailwind-bootstrap-grid'),
]
```
But this does.
```
plugins: [
     require('tailwind-bootstrap-grid')(),
]
```
**Notice the () parenthesis after require**, idk what difference it makes, maybe without () it doesn't adds its rules to Tailwind's rules.
Anyway its kinda something to notice, bcz  Tailwind's forms plugin work without parenthesis
```
plugins: [
     require('@tailwindcss/forms'),
]
```
Thnx for the replies though...

**Comment by karolis-sh** [comment]
> Its funny enough, I noticed it very late.
> 
> This doesn't work
> 
> ```
> plugins: [
>      require('tailwind-bootstrap-grid'),
> ]
> ```
> 
> But this does.
> 
> ```
> plugins: [
>      require('tailwind-bootstrap-grid')(),
> ]
> ```
> 
> **Notice the () parenthesis after require**, idk what difference it makes, maybe without () it doesn't adds its rules to Tailwind's rules.
> Anyway its kinda something to notice, bcz Tailwind's forms plugin work without parenthesis
> 
> ```
> plugins: [
>      require('@tailwindcss/forms'),
> ]
> ```
> 
> Thnx for the replies though...

Yeah, the `require('tailwind-bootstrap-grid')()` syntax is required, because you can pass options (https://github.com/karolis-sh/tailwind-bootstrap-grid#installation). At first glance, I thought `@tailwindcss/forms` doesn't need function invocation, because it doesn't have any options, but it's not true - https://github.com/tailwindlabs/tailwindcss-forms#using-classes-instead-of-element-selectors. 

I see tailwind added a helper package `tailwindcss/plugin` (https://tailwindcss.com/docs/plugins), to achieve `require('@tailwindcss/forms')` + `require('@tailwindcss/forms')()` usecase. I will create a separate issue to support that in `tailwind-bootstrap-grid` next release. Thanks for the follow up 👍
